In [1]:
%load_ext autoreload
%autoreload 2
import sys
import json
import os
import numpy as np
from collections import defaultdict
from pathlib import Path
project_root = Path(os.getcwd()).parent.parent
print(f'当前目录: {project_root}')
sys.path.append(str(project_root))

当前目录: /Users/steven/Documents/GridProjects/MAGRL

定义生成算例的时间跨度，基于的IEEE NBus算例和输出目录

In [2]:
days = 1
steps_per_day = 96
seed = 123
feeder = "case33bw"
out_dir = os.path.join(project_root, f"data/generated/ieee_{feeder}")

In [3]:
from scripts.generate_env_data import generate_ieee_env_data
from scenario.base_scenario import ScenarioConfig
cfg = ScenarioConfig(days=days)
generate_ieee_env_data(feeder, out_dir, cfg, seed)

Loading IEEE standard case: case33bw
Topology configured: 33 buses, 35 loads (including 3 PVs as negative loads), 3 storages.
Environment logic topology successfully explicitly saved to: /Users/steven/Documents/GridProjects/MAGRL/data/generated/ieee_case33bw/topology
Data generation complete! Saved loads to: /Users/steven/Documents/GridProjects/MAGRL/data/generated/ieee_case33bw

--- 数据分析摘要 ---
>> 总用电负荷: 最大 = 3.29 MW, 最小 = 2.11 MW, 平均 = 2.59 MW
>> 总光伏发电: 最大 = 5.58 MW, 最小 = 0.00 MW, 平均 = 1.66 MW
>> 净负荷 (Load - Gen): 最大 = 3.29 MW, 最小 = -3.14 MW (如果是负值说明出现功率向主网红反灌倒送)

 数据时序分析图已保存至: /Users/steven/Documents/GridProjects/MAGRL/data/generated/ieee_case33bw/total_power_curve.png

In [6]:
import pandapower as pp
import pandas as pd
net = pp.from_pickle(os.path.join(out_dir, 'topology.p'))
pp.runpp(net)
net.storage

,name,bus,p_mw,q_mvar,sn_mva,soc_percent,min_e_mwh,max_e_mwh,scaling,in_service,type,max_p_mw
0,Storage_bus17,17,0.0,0.0,NaN,NaN,0.0,4.0,1.0,True,None,1.0
1,Storage_bus16,16,0.0,0.0,NaN,NaN,0.0,4.0,1.0,True,None,1.0
2,Storage_bus15,15,0.0,0.0,NaN,NaN,0.0,4.0,1.0,True,None,1.0

In [7]:
net.res_ext_grid

       p_mw    q_mvar
0  3.917677  2.435141